### ISSUE TITLE
Compatibility with redmine_tags 

### ISSUE THREAD

**Issue by monakov-y** [Loriowar/redmine_issues_tree#24]
The issue is the same as described in redmine_tags project: https://github.com/ixti/redmine_tags/issues/45 (and finally resolved in https://github.com/ande3577/redmine-graphs-plugin/issues/12)
However, the solution which was proposed to redmine-graphs-plugin perfectly works with redmine_issues_tree. If I add
``` ruby
# WARNING: BIG HACK {{{
    IssuesController._helpers.included_modules.each do |mod|
      helper mod
    end
# }}}
```
to `app/controllers/issues_trees_controller.rb` then everything works without errors. 

PS. It is really great plugin, thanks!

**Comment by monakov-y** [comment]
I've used redmine_issues_tree from the actual master with redmine 3.1 and latest redmine_tags.

**Comment by Loriowar** [comment]
As I understand, you need all helpers from Issue on tree_view page for correct works of functions from _redmine_tags_ plugin. But idea of tree_view is in separate controller and in some kind of independency from _Issue_. Because this view is only looks like default(plain) issues view, but in reality this is a separate part with own logic. Some actions from _Issues_ are completely broken on _tree_view_, other one I'm not test yet. That is why I remove all helpers and action related with _Issues_, but doesn't needed for functionality of _tree_view_. If you want it and you really understand what you want you can patch _IssuesTreesController_ and add anything what you need. But this is for you own risk.

Best way to patch controller is follows: looks at `lib/redmine_issues_tree/issue_patch.rb` file, make same one for IssuesTreesController and add you source code into `included do` section. After this you need to send this module to _IssuesTreesController_. This action you can do, for example, by the [follows way]( https://github.com/Loriowar/redmine_issues_tree/blob/master/init.rb#L15). And thats all.

This approach is more acceptable, because you doesn't make a monkey-patch of source code of plugin and in future you can easily merge new changes into your local copy of plugin without any conflicts. But remember, in fact you make absolutely same actions as you described, but on more elegant way.

And thanks for using this plugin!
