### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by paklich** [Loriowar/redmine_issues_tree#29]
Hi, there is the way to change sort order for task and theirs subtasks? Now it's sorted by issue number (desc). Is it possible to change sort field and sort order? To issue name for example?

**Comment by Loriowar** [comment]
Hi! For now, there is no way to change order for tasks and subtasks. Because this is single table of issues. Different order of sorting can be implemented through completely rewriting issues page or with usage of some js-magic. In both cases tree view become completely different in compare with initial issues page. So, this feature looks like separate tree view page without looking back on Redmine. As result: I have no plans for implement something like this feature for now, but I'll be glad to help in implement this and/or receive a pull-request with implemented functions.

**Comment by paklich** [comment]
Sad. But anyway it's very usefull plugin. Thank you.

**Comment by Loriowar** [comment]
Impossible without major changes in Redmine. Closed.
