### ISSUE TITLE
Tree View icon doesn't appear

### ISSUE THREAD

**Issue by nviel** [Loriowar/redmine_issues_tree#33]
Hello Ivan,

I'm sorry to be a 'yet an other guy with problem of icon', but I think I have do my best.

I tested several combination with no success:
redmine 3.2.2 with branch 3.2.x and 3.1.0 (ruby 2.2.4 using rbenv)
redmine 3.2.0 with branch 3.2.x and 3.1.0 (ruby 2.2.4 using rbenv)

Of course, redmine_issues_tree was the only plugin in order to be sure there was no nasty interactions.
* I got redmine here: http://www.redmine.org/releases/redmine-3.2.2.tar.gz,
* just configure the database,
* clone the plugin in the plugins directory and checkout the right branch,
* `bundle install --without development test rmagick`

then I just started the webrick server:
`bundle exec rails server webrick -e production --binding=0.0.0.0`

... And I have even thought to empty my browser cache with a ctrl-F5 ;-).

**Comment by Loriowar** [comment]
Absence of icon can appear in two cases:
* plugin not loaded (you have custom configuration of your Redmine or some other magic in loading process of plugins);
* you redefine template `issues/index` somewhere else in your installation; usually this situation appear due to combination with other plugins, but if you doesn't have them - this is strange situation.

Last variant: you start server in production. Maybe icon appear in development mode? If yes, then problem exist on your installation, not in plugin.

**Comment by nviel** [comment]
Ok, it works now, even if I don't realy undersand what was wrong.
Thanks for the plugin and your answer. 
I will try now to make parent tickets not be filtered in order to keep the tree structure cohérent regardless of the filter.

bye
