### ISSUE TITLE
Error after a redirect to the tree view from the issues index

### ISSUE THREAD

**Issue by enegriy** [Loriowar/redmine_issues_tree#45]
![image](https://cloud.githubusercontent.com/assets/3262460/21422992/a60dbf2c-c84b-11e6-91f7-996fef2c4016.png)

**Comment by Loriowar** [comment]
This is a feature, not a bug. Because there is no way to apply a group condition in the tree view. I.e. I don't know how to group a data on the tree view. If you can describe this action, please, do that.

One more thing. This is an information message, not an error. Maybe will be better to make a yellow warning message box instead of a current red error box.

PS: English is a preferable language due to peoples from different countries and from different places around the World. Most part of them know English, less - Russian.

**Comment by Loriowar** [comment]
Error message replased with warning message.
